DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS events;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
  );

CREATE TABLE links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  webname TEXT NOT NULL,
  website TEXT NOT NULL
  );

CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  eventname TEXT NOT NULL,
  organization TEXT NOT NULL,
  link TEXT NOT NULL,
  deadline TEXT NOT NULL,
  fee TEXT NOT NULL
  );